ACCOUNT_ID = 2000122593
SYMBOL = "EURUSDrfd"
MAGIC = 202603

MAX_DAILY_LOSS = 400.0
MAX_DAILY_TRADES = 5
MAX_OPEN_POSITIONS = 1
RISK_PERCENT = 1.0
RISK_ATR_ADAPTIVE = True
MAX_LOT = 0.5
MAX_SPREAD_PIPS = 5.0
MAX_SLIPPAGE = 20

BREAKEVEN_ATR = 0.5
TRAILING_STEP_ATR = 0.2
TRAILING_ACTIVATION_ATR = 0.7

MIN_CONFIDENCE = 7
GPT_TIMEOUT = 60
GPT_MAX_RETRIES = 2

CORR_WEIGHT = 1.0
TECH_WEIGHT = 1.0

NIGHT_START = 0
NIGHT_END = 0
WEEKEND_STOP = True
CLOSE_BEFORE_NEWS_MINUTES = 30
CLOSE_FRIDAY_HOUR = 20

ENABLE_EXTERNAL_SIGNALS = False
WEBHOOK_PORT = 5000

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
TELEGRAM_HOURLY_STATUS = False

LOG_DIR = "logs"
TRADE_HISTORY_FILE = "logs/trade_history.json"
DB_FILE = "logs/autopilot.db"

CORR_RECALC_HOURS = 24
CORR_WINDOW = 60

AUTO_OPTIMIZE = True
OPTIMIZE_INTERVAL_DAYS = 7
OPTIMIZE_MIN_TRADES = 20
